apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: {{ app.name }}
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: pensjonsamhandling
  secretName: {{ app.name }}-unleash-api-token
  environment: {{ unleash.environment }}
