<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:bons1="http://nav-lib-pen/no/nav/lib/pen/gbo" xmlns:tns="http://nav-lib-pen/no/nav/lib/pen/inf/BehandleDodsmeldinger" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="BehandleDodsmeldinger" targetNamespace="http://nav-lib-pen/no/nav/lib/pen/inf/BehandleDodsmeldinger">
    <wsdl:types>
    <xsd:schema targetNamespace="http://nav-lib-pen/no/nav/lib/pen/inf/BehandleDodsmeldinger" xmlns:bons1="http://nav-lib-pen/no/nav/lib/pen/gbo" xmlns:tns="http://nav-lib-pen/no/nav/lib/pen/inf/BehandleDodsmeldinger" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://nav-lib-pen/no/nav/lib/pen/gbo" schemaLocation="../gbo/GBOBehandleDodsmeldinger.xsd"/>
            <xsd:element name="behandleDodsmeldinger">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="behandleDodsmeldingerRequest" nillable="true" type="bons1:GBOBehandleDodsmeldinger"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
        </xsd:schema>
  </wsdl:types>
    <wsdl:message name="behandleDodsmeldingerRequestMsg">
    <wsdl:part element="tns:behandleDodsmeldinger" name="behandleDodsmeldingerParameters"/>
  </wsdl:message>
    <wsdl:portType name="BehandleDodsmeldinger">
        <wsdl:operation name="behandleDodsmeldinger">
      <wsdl:input message="tns:behandleDodsmeldingerRequestMsg" name="behandleDodsmeldingerRequest"/>
    </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
