<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SAMTjenestepensjonWSEXP_SAMTjenestepensjonHttp_Service" targetNamespace="http://nav-cons-sto-sam-tjenestepensjon/no/nav/inf/Binding" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://nav-cons-sto-sam-tjenestepensjon/no/nav/inf" xmlns:this="http://nav-cons-sto-sam-tjenestepensjon/no/nav/inf/Binding" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <import namespace="http://nav-cons-sto-sam-tjenestepensjon/no/nav/inf" location="no/nav/inf/SAMTjenestepensjon.wsdl">
    </import>
  <binding name="SAMTjenestepensjonWSEXP_SAMTjenestepensjonHttpBinding" type="Port_0:SAMTjenestepensjon">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="finnTjenestepensjonsforhold">
      <soap:operation soapAction=""/>
      <input name="finnTjenestepensjonsforholdRequest">
        <soap:body use="literal"/>
      </input>
      <output name="finnTjenestepensjonsforholdResponse">
        <soap:body use="literal"/>
      </output>
      <fault name="faultStoGenerisk">
        <soap:fault name="faultStoGenerisk" use="literal"/>
      </fault>
      <fault name="faultStoTomDatoForanFomDato">
        <soap:fault name="faultStoTomDatoForanFomDato" use="literal"/>
      </fault>
      <fault name="faultStoElementetFinnesIkke">
        <soap:fault name="faultStoElementetFinnesIkke" use="literal"/>
      </fault>
    </operation>
    <operation name="lagreTjenestepensjonYtelse">
      <soap:operation soapAction=""/>
      <input name="lagreTjenestepensjonYtelseRequest">
        <soap:body use="literal"/>
      </input>
      <output name="lagreTjenestepensjonYtelseResponse">
        <soap:body use="literal"/>
      </output>
      <fault name="faultStoGenerisk">
        <soap:fault name="faultStoGenerisk" use="literal"/>
      </fault>
      <fault name="faultStoElementetHarOverlappendePeriode">
        <soap:fault name="faultStoElementetHarOverlappendePeriode" use="literal"/>
      </fault>
      <fault name="faultStoElementetErDuplikat">
        <soap:fault name="faultStoElementetErDuplikat" use="literal"/>
      </fault>
      <fault name="faultStoKanIkkeSletteIverksattDato">
        <soap:fault name="faultStoKanIkkeSletteIverksattDato" use="literal"/>
      </fault>
      <fault name="faultStoTomDatoForanFomDato">
        <soap:fault name="faultStoTomDatoForanFomDato" use="literal"/>
      </fault>
    </operation>
    <operation name="opprettTjenestepensjonYtelse">
      <soap:operation soapAction=""/>
      <input name="opprettTjenestepensjonYtelseRequest">
        <soap:body use="literal"/>
      </input>
      <output name="opprettTjenestepensjonYtelseResponse">
        <soap:body use="literal"/>
      </output>
      <fault name="faultStoGenerisk">
        <soap:fault name="faultStoGenerisk" use="literal"/>
      </fault>
      <fault name="faultStoElementetHarOverlappendePeriode">
        <soap:fault name="faultStoElementetHarOverlappendePeriode" use="literal"/>
      </fault>
      <fault name="faultStoElementetErDuplikat">
        <soap:fault name="faultStoElementetErDuplikat" use="literal"/>
      </fault>
      <fault name="faultStoKanIkkeSletteIverksattDato">
        <soap:fault name="faultStoKanIkkeSletteIverksattDato" use="literal"/>
      </fault>
      <fault name="faultStoTomDatoForanFomDato">
        <soap:fault name="faultStoTomDatoForanFomDato" use="literal"/>
      </fault>
    </operation>
    <operation name="slettTjenestepensjonYtelse">
      <soap:operation soapAction=""/>
      <input name="slettTjenestepensjonYtelseRequest">
        <soap:body use="literal"/>
      </input>
      <output name="slettTjenestepensjonYtelseResponse">
        <soap:body use="literal"/>
      </output>
      <fault name="faultStoGenerisk">
        <soap:fault name="faultStoGenerisk" use="literal"/>
      </fault>
      <fault name="faultStoElementetErUgyldig">
        <soap:fault name="faultStoElementetErUgyldig" use="literal"/>
      </fault>
    </operation>
    <operation name="opprettTjenestepensjonsforhold">
      <soap:operation soapAction=""/>
      <input name="opprettTjenestepensjonsforholdRequest">
        <soap:body use="literal"/>
      </input>
      <output name="opprettTjenestepensjonsforholdResponse">
        <soap:body use="literal"/>
      </output>
      <fault name="faultStoGenerisk">
        <soap:fault name="faultStoGenerisk" use="literal"/>
      </fault>
      <fault name="faultStoElementetErDuplikat">
        <soap:fault name="faultStoElementetErDuplikat" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="SAMTjenestepensjonWSEXP_SAMTjenestepensjonHttpService">
    <port name="SAMTjenestepensjonWSEXP_SAMTjenestepensjonHttpPort" binding="this:SAMTjenestepensjonWSEXP_SAMTjenestepensjonHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-sto-sam-tjenestepensjonWeb/sca/SAMTjenestepensjonWSEXP"/>
    </port>
  </service>
</definitions>
