name: "Build and deploy"

on:
  push

env:
  IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
  build:
    permissions:
      contents: "read"
      checks: "write"
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      version: ${{ steps.version.outputs.version }}
      image: "${{ steps.login.outputs.registry }}/pensjon-elsam-minibuss/pensjon-elsam-minibuss:${{ env.VERSION }}"

    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: version
        shell: bash
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=12 HEAD)
          export VERSION="$TIME-$COMMIT"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - uses: docker/setup-buildx-action@v3

      - name: Build
        shell: bash
        run: |
          mvn -Drevision="${VERSION}" package
        env:
          TZ: "Europe/Oslo"

      - name: Upload surefire reports on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports
          path: ${{ github.workspace }}/**/target/surefire-reports/*
          retention-days: 5

      - name: Upload HotSpot Fatal Error logs on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: hotspot-fatal-error-logs
          path: ${{ github.workspace }}/**/hs_err_pid*.log
          retention-days: 5

      - name: NAIS login
        uses: nais/login@v0
        id: login
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: pensjonsamhandling

      - name: "Build and publish Docker image"
        id: build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: "${{ steps.login.outputs.registry }}/pensjon-elsam-minibuss/pensjon-elsam-minibuss:${{ env.VERSION }},${{ steps.login.outputs.registry }}/pensjon-elsam-minibuss/pensjon-elsam-minibuss:main"
          push: true
          cache-from: |
            "type=registry,ref=${{ steps.login.outputs.registry }}/pensjon-elsam-minibuss/pensjon-elsam-minibuss:main"
          cache-to: type=inline

      - name: Generate SBOM, attest and sign image
        uses: nais/attest-sign@v1
        with:
          image_ref: ${{ steps.login.outputs.registry }}/pensjon-elsam-minibuss/pensjon-elsam-minibuss}}@${{ steps.build_push.outputs.digest }}
          sbom: target/classes/META-INF/sbom/application.cdx.json

  deploy:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    needs: [build]
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        include:
          - vars: .nais/vars-dev-q2.yaml
            cluster: dev-fss

    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: "${{ needs.build.outputs.image }}"
          RESOURCE: .nais/nais.yaml
          CLUSTER: '${{ matrix.cluster }}'
          VARS: ${{matrix.vars}}
